name: flashfictory
favicon: null
layout_spectrum: 0.18034
typography_spectrum: 0.1247
title: Flash Fictory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89abc4'
    - '#4c5425'
    - '#000e00'
    - '#f6472a'
    - '#e3cf19'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.903800813248381
  rhythmicContrast: 0.75
purpose: []
