name: liamatchison
favicon: null
layout_spectrum: 0.65749
typography_spectrum: 0.32418
title: This Experiment is Tedious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89abc4'
    - '#4c5425'
    - '#000e00'
    - '#f6472a'
    - '#e3cf19'
  brandStrength: 0.75
  lightness: 0.2625685320235789
  saturation: 0.903800813248381
  rhythmicContrast: 0.75
purpose: []
